name: Cache Nix Action
description: Backup and Restore of the Nix Store
author: Scaffoldly <github.com/scaffoldly>
branding:
  icon: archive
  color: gray-dark
inputs:
  key:
    description: "Cache key"
    required: false
    default: "${{ runner.os }}-nix-store"
runs:
  using: "node24"
  main: "dist/main/index.js"
  post: "dist/post/index.js"
